### PR TITLE
Adding Forms

### PR DESCRIPTION
**Pull request by siddartha19**

### CODE REVIEW

**Comment by ankit039** [comment]
Hello open source contributor,
Can you explain what exactly are you tring to do..so far?

**Comment by siddartha19** [comment]
I have added the same form Multiple times. So I have changed back.

**Comment by ankit039** [comment]
as i can see you have deleted all the suff?

**Comment by siddartha19** [comment]
Yeah so don't want to put the empty things in that repo so I deleted that stuff

**Pull request closed without merging**
